### ISSUE TITLE
linker error in `em1d` and `em1ds`

### ISSUE THREAD

**Issue by berceanu** [ricardo-fonseca/zpic#2]
Running `make all` inside `em1ds` results in 

```
gcc -c -Ofast -std=c99 -pedantic filter.c -o filter.o
gcc -c -Ofast -std=c99 -pedantic charge.c -o charge.o
gcc -c -Ofast -std=c99 -pedantic current.c -o current.o
gcc -c -Ofast -std=c99 -pedantic emf.c -o emf.o
gcc -c -Ofast -std=c99 -pedantic particles.c -o particles.o
gcc -c -Ofast -std=c99 -pedantic grid.c -o grid.o
gcc -c -Ofast -std=c99 -pedantic fft.c -o fft.o
gcc -c -Ofast -std=c99 -pedantic random.c -o random.o
gcc -c -Ofast -std=c99 -pedantic timer.c -o timer.o
gcc -c -Ofast -std=c99 -pedantic main.c -o main.o
gcc -c -Ofast -std=c99 -pedantic simulation.c -o simulation.o
gcc -c -Ofast -std=c99 -pedantic zdf.c -o zdf.o
gcc    -Ofast -std=c99 -pedantic -lm filter.o charge.o current.o emf.o particles.o grid.o fft.o random.o timer.o main.o simulation.o zdf.o -o zpic
filter.o: In function `filter_set':
filter.c:(.text+0x3f8): undefined reference to `__expf_finite'
emf.o: In function `lon_env':
emf.c:(.text+0x26b): undefined reference to `cos'
emf.o: In function `emf_add_laser':
emf.c:(.text+0x360): undefined reference to `sincosf'
emf.c:(.text+0x3f7): undefined reference to `cos'
emf.c:(.text+0x441): undefined reference to `cos'
emf.o: In function `advance_psatd':
emf.c:(.text+0x1874): undefined reference to `sincosf'
fft.o: In function `fft_init_cfg':
fft.c:(.text+0x2117): undefined reference to `sincos'
fft.o: In function `fftr_init_cfg':
fft.c:(.text+0x267b): undefined reference to `sincos'
random.o: In function `rand_norm':
random.c:(.text+0x14b): undefined reference to `__log_finite'
collect2: error: ld returned 1 exit status
Makefile:26: recipe for target 'zpic' failed
make: *** [zpic] Error 1
```
System: Ubuntu 18.04 LTS, gcc 7.3.0

**Comment by berceanu** [comment]
Also, inside `em1d`, I get

```
gcc -c -std=c99 -pedantic current.c -o current.o
gcc -c -std=c99 -pedantic emf.c -o emf.o
gcc -c -std=c99 -pedantic particles.c -o particles.o
gcc -c -std=c99 -pedantic random.c -o random.o
gcc -c -std=c99 -pedantic timer.c -o timer.o
gcc -c -std=c99 -pedantic main.c -o main.o
gcc -c -std=c99 -pedantic simulation.c -o simulation.o
gcc -c -std=c99 -pedantic zdf.c -o zdf.o
gcc -std=c99 -pedantic -lm current.o emf.o particles.o random.o timer.o main.o simulation.o zdf.o -o zpic
emf.o: In function `lon_env':
emf.c:(.text+0x404): undefined reference to `sin'
emf.c:(.text+0x4fb): undefined reference to `sin'
emf.o: In function `emf_add_laser':
emf.c:(.text+0x6b4): undefined reference to `cos'
emf.c:(.text+0x6cf): undefined reference to `sin'
emf.c:(.text+0x7bc): undefined reference to `cos'
emf.c:(.text+0x845): undefined reference to `cos'
emf.c:(.text+0x8dd): undefined reference to `cos'
emf.c:(.text+0x966): undefined reference to `cos'
particles.o: In function `spec_np_inj':
particles.c:(.text+0xae1): undefined reference to `ceil'
particles.o: In function `spec_set_x':
particles.c:(.text+0x1123): undefined reference to `sqrt'
particles.c:(.text+0x143d): undefined reference to `sqrt'
particles.o: In function `spec_advance':
particles.c:(.text+0x2ec2): undefined reference to `sqrtf'
particles.c:(.text+0x3188): undefined reference to `sqrtf'
random.o: In function `rand_norm':
random.c:(.text+0x1a3): undefined reference to `log'
random.c:(.text+0x1bd): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
Makefile:30: recipe for target 'zpic' failed
make: *** [zpic] Error 1
```

**Comment by ricardo-fonseca** [comment]
Hi Andrei

On some systems the library libm (-lm) must be included after the object files. We are looking for a general solution, but in the mean time changing the Makefile so that it reads like this:

  27   │
  28   │ $(TARGET) : $(OBJ)
  29 ~ │     $(CC) $(CFLAGS) $(OBJ) -o $@ $(LDFLAGS)
  30   │
(
(Notice that $(LDFLAGS) changed position) should fix the issue.

All the best,
Ricardo

—
Ricardo Fonseca

Full Professor | Professor Catedrático
DCTI - Dep. Ciências e Tecnologias da Informação
ISCTE - Instituto Universitário de Lisboa
Av. Forças Armadas
1649-026 Lisboa
Portugal

tel: +351 21 7650544    ext: 220107
web: https://ciencia.iscte-iul.pt/rpafa/en

On 16 Mar 2019, at 12:00, Andrei Berceanu <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, inside em1d, I get

gcc -c -std=c99 -pedantic current.c -o current.o
gcc -c -std=c99 -pedantic emf.c -o emf.o
gcc -c -std=c99 -pedantic particles.c -o particles.o
gcc -c -std=c99 -pedantic random.c -o random.o
gcc -c -std=c99 -pedantic timer.c -o timer.o
gcc -c -std=c99 -pedantic main.c -o main.o
gcc -c -std=c99 -pedantic simulation.c -o simulation.o
gcc -c -std=c99 -pedantic zdf.c -o zdf.o
gcc -std=c99 -pedantic -lm current.o emf.o particles.o random.o timer.o main.o simulation.o zdf.o -o zpic
emf.o: In function `lon_env':
emf.c:(.text+0x404): undefined reference to `sin'
emf.c:(.text+0x4fb): undefined reference to `sin'
emf.o: In function `emf_add_laser':
emf.c:(.text+0x6b4): undefined reference to `cos'
emf.c:(.text+0x6cf): undefined reference to `sin'
emf.c:(.text+0x7bc): undefined reference to `cos'
emf.c:(.text+0x845): undefined reference to `cos'
emf.c:(.text+0x8dd): undefined reference to `cos'
emf.c:(.text+0x966): undefined reference to `cos'
particles.o: In function `spec_np_inj':
particles.c:(.text+0xae1): undefined reference to `ceil'
particles.o: In function `spec_set_x':
particles.c:(.text+0x1123): undefined reference to `sqrt'
particles.c:(.text+0x143d): undefined reference to `sqrt'
particles.o: In function `spec_advance':
particles.c:(.text+0x2ec2): undefined reference to `sqrtf'
particles.c:(.text+0x3188): undefined reference to `sqrtf'
random.o: In function `rand_norm':
random.c:(.text+0x1a3): undefined reference to `log'
random.c:(.text+0x1bd): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
Makefile:30: recipe for target 'zpic' failed
make: *** [zpic] Error 1

**Comment by ax3l** [comment]
Oh, just saw this now.
It's save to generally apply PR #3 and you can decide if you also want to merge #4 since most `Makefile`s currently default to `gcc`.
